version: "3"

services:
  front:
    build: ./
    image: hok-front:1.0.2
    ports:
      - "3000:3000"
    volumes:
      - front-data:/app
    restart: always
    entrypoint: serve -s

volumes:
  front-data:


